name: ts3-checker-rs test CI

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Check if rust is installed
        run: rustc --version